### ISSUE TITLE
I got an error while installing bundle:

### ISSUE THREAD

**Issue by peefour** [dynport/dockland#1]
hi,

I got an error while installing bundle:

----8<---
root@vhost /opt/dockland # bundle
Fetching gem metadata from https://rubygems.org/......
Fetching gem metadata from https://rubygems.org/..
Using addressable (2.3.4)
Using archive-tar-minitar (0.5.2)
Installing ffi (1.8.1)
Installing childprocess (0.3.9)
Installing coderay (1.0.9)
Installing safe_yaml (0.9.3)
Installing crack (0.4.0)
Installing erubis (2.7.0)
Installing fakeweb (1.3.0)
Installing multipart-post (1.2.0)
Installing faraday (0.8.7)
Installing i18n (0.6.4)
Installing json (1.7.7)
Installing kgio (2.8.0)
Installing log4r (1.1.10)
Installing method_source (0.8.1)
Installing multi_json (1.7.3)
Using net-http-persistent (2.8)
Installing net-ssh (2.2.2)
Installing net-scp (1.0.4)
Installing oj (2.0.13)
Installing slop (3.4.5)
Installing pry (0.9.12.2)
Installing rack (1.5.2)
Installing puma (2.0.1)
Gem::Installer::ExtensionBuildError: ERROR: Failed to build gem native extension                                                                                                                     .

```
    /usr/bin/ruby1.9.1 extconf.rb
```

creating Makefile

make
compiling mini_ssl.c
In file included from mini_ssl.c:2:0:
/usr/include/ruby-1.9.1/ruby/backward/rubyio.h:2:2: warning: #warning use "ruby/                                                                                                                     io.h" instead of "rubyio.h" [-Wcpp]
 #warning use "ruby/io.h" instead of "rubyio.h"
  ^
mini_ssl.c:3:25: fatal error: openssl/bio.h: No such file or directory
 #include <openssl/bio.h>
                         ^
compilation terminated.
make: **\* [mini_ssl.o] Error 1

Gem files will remain installed in /var/lib/gems/1.9.1/gems/puma-2.0.1 for inspe                                                                                                                     ction.
Results logged to /var/lib/gems/1.9.1/gems/puma-2.0.1/ext/puma_http11/gem_make.o                                                                                                                     ut

An error occurred while installing puma (2.0.1), and Bundler cannot continue.
Make sure that `gem install puma -v '2.0.1'` succeeds before bundling.
root@vhost /opt/dockland #

**Comment by LespiletteMaxime** [comment]
To fix this just install libssl-dev

**Comment by peefour** [comment]
thanks i will try it!
